### ISSUE TITLE
ConfigParser.NoSectionError

### ISSUE THREAD

**Issue by iamspire** [keithjjones/fileintel#2]
Having this issue when running your sample config. I'm not too sure how to get the methods into pythons configs, but perhaps there is a step missing?

```
~/fileintel$ sudo python fileintel.py sampleconf.conf sampledata/smallerlist.txt -n > sampledata/smallerlist.csv
Traceback (most recent call last):
  File "fileintel.py", line 108, in <module>
    vtpublicapi = ConfigFile.get('VirusTotal', 'PublicAPI')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'VirusTotal'
```

**Comment by keithjjones** [comment]
That's weird.  It's definitely in there: 

https://github.com/keithjjones/fileintel/blob/master/sampleconfig.conf#L1

Did you fill out the API key values?

**Comment by iamspire** [comment]
Do the API key values HAVE to be filled out? Currently just wanted to test the NSRL function.. tried commenting out the other functions to see if that works too and no luck. Perhaps I commented out the wrong area?

**Comment by keithjjones** [comment]
Commenting things out in the config file is probably the issue.  Even if you don't use the modules, I think it still expects some value to be there.  That is why I provided a sample config file.

You need API keys for any modules that are called.  I can't remember, without going through the code, if there are some minimal calls.

**Comment by iamspire** [comment]
Oh what I meant was I tried it without commenting, and with and had the same result. The time I ran it which I posted up top was ran without any commenting anything out. I haven't tried punching in any random values though for the api key. Ill give that a shot!

**Comment by keithjjones** [comment]
It's looking for your VT API in that call.  Just create a free VT account and use that key so it works.

**Comment by keithjjones** [comment]
Well, actually, your error says there is no section.  So either you commented something out or aren't using a valid conf file?

**Comment by keithjjones** [comment]
There has been no activity on this in quite a while.  I'm closing.  Reopen if you are still having issues.
